FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=password
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=10000
ENV N8N_PROTOCOL=http
ENV WEBHOOK_URL=https://n8n-server.onrender.com/
ENV GENERIC_TIMEZONE=Europe/Madrid

EXPOSE 10000

CMD ["n8n", "start"]
