services:
  - type: web
    name: n8n-server
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_HOST
        value: n8n-server.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-server.onrender.com
