services:
  - type: web
    name: n8n-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: GENERIC_TIMEZONE
        value: Europe/Madrid
